"""
Gemini image generation module for Omelet.

Uses Google Gemini API to generate images from text prompts,
with special support for blog featured images.
"""

from pathlib import Path

import cv2
import numpy as np
from google import genai
from google.genai import types


STYLE_PROMPTS = {
    "academic": (
        "Black and white line art, textbook figure style, clean white or light gray background, "
        "simple geometric shapes and icons, hand-drawn sketch aesthetic, academic labels, "
        "like a figure from O'Reilly book or IEEE paper. Include a 'Figure 1:' caption at bottom"
    ),
    "tech": (
        "Dark blue/purple gradient background, modern minimalist tech illustration style, "
        "glowing geometric elements, professional quality"
    ),
    "minimal": (
        "Clean white background, simple line art, minimalist design, elegant and professional"
    ),
    "colorful": (
        "Vibrant gradient background, modern flat design, bold colors, eye-catching composition"
    ),
}


class GeminiImageGenerator:
    """Generate images using Google Gemini API."""

    def __init__(self, api_key: str, model: str = "gemini-3-pro-image-preview"):
        self.client = genai.Client(api_key=api_key)
        self.model = model

    def generate_image(self, prompt: str, output_path: str) -> str:
        """
        Generate an image from a text prompt and save it.

        Args:
            prompt: Text description of the image to generate.
            output_path: Path where the image will be saved.

        Returns:
            Path to the saved image file.

        Raises:
            RuntimeError: If no image was generated.
        """
        response = self.client.models.generate_content(
            model=self.model,
            contents=prompt,
            config=types.GenerateContentConfig(
                response_modalities=["IMAGE", "TEXT"]
            ),
        )

        if response.candidates:
            for part in response.candidates[0].content.parts:
                if part.inline_data:
                    output_file = Path(output_path)
                    output_file.parent.mkdir(parents=True, exist_ok=True)

                    with open(output_file, "wb") as f:
                        f.write(part.inline_data.data)

                    self._strip_metadata(output_file)
                    return str(output_file)

        raise RuntimeError("No image was generated by Gemini")

    @staticmethod
    def _strip_metadata(image_path: Path) -> None:
        """Read image pixels with OpenCV and rewrite to strip all metadata."""
        img = cv2.imread(str(image_path), cv2.IMREAD_UNCHANGED)
        if img is not None:
            cv2.imwrite(str(image_path), img)

    def generate_blog_featured_image(
        self, topic: str, output_path: str, style: str = "academic"
    ) -> str:
        """
        Generate a featured image for a blog post.

        Args:
            topic: The blog topic/title.
            output_path: Path where the image will be saved.
            style: Image style preset (academic, tech, minimal, colorful).

        Returns:
            Path to the saved image file.
        """
        style_desc = STYLE_PROMPTS.get(style, STYLE_PROMPTS["academic"])

        prompt = (
            f"Create a featured image for a programming blog about: {topic}\n\n"
            f"Requirements:\n"
            f"- {style_desc}\n"
            f"- Professional quality suitable as blog hero image\n"
            f"- 16:9 aspect ratio composition\n"
            f"- Clean, educational aesthetic suitable for tech blog"
        )

        return self.generate_image(prompt, output_path)
