import base64
from pathlib import Path

import cv2
from openai import OpenAI


STYLE_PROMPTS = {
    "academic": (
        "Black and white line art, textbook figure style, clean white or light gray background, "
        "simple geometric shapes and icons, hand-drawn sketch aesthetic, academic labels, "
        "like a figure from O'Reilly book or IEEE paper. Include a 'Figure 1:' caption at bottom"
    ),
    "tech": (
        "Dark blue/purple gradient background, modern minimalist tech illustration style, "
        "glowing geometric elements, professional quality"
    ),
    "minimal": (
        "Clean white background, simple line art, minimalist design, elegant and professional"
    ),
    "colorful": (
        "Vibrant gradient background, modern flat design, bold colors, eye-catching composition"
    ),
    "constructivism": (
        "Russian Constructivism poster style merged with modern minimalism. "
        "Asymmetric composition with strong 45-degree diagonal energy. "
        "Color palette strictly limited: deep red (#C8102E), pure black, off-white cream (#F5F1E8), "
        "single accent of deep navy blue. Flat colors only, NO gradients. "
        "Bold geometric shapes overlapping (rectangles, circles, triangles). "
        "Heavy sans-serif block typography for any text elements. "
        "Diagonal red wedge composition reminiscent of El Lissitzky's 'Beat the Whites with the Red Wedge' (1919). "
        "Generous negative space. High contrast, propaganda-poster boldness, machine-aesthetic. "
        "Reference: Rodchenko, El Lissitzky, Mayakovsky 1919-1925 designs. "
        "NOT generic flat design, NOT Bauhaus pastel — must have aggressive constructivist energy."
    ),
    "socialist-realism": (
        "Soviet Socialist Realism propaganda poster style merged with modern minimalism. "
        "Monumental, heroic, optimistic composition with one central idealized figure "
        "(scientist, engineer, or worker) in a confident heroic three-quarter pose, "
        "looking forward with determination. Slightly low camera angle for monumental feel. "
        "Painterly brush strokes, NOT photorealistic. Idealized realism. "
        "Dramatic chiaroscuro lighting from upper left, casting confident shadow. "
        "Color palette: dominant deep crimson red (#A8121E), warm cream/parchment background (#E8DCC4), "
        "strong black outlines, golden ochre highlights (#C4923A), muted teal accents. "
        "Limited to 5 colors max. Bright optimistic palette. "
        "Background elements (minimalist): rising sun with red rays, abstracted industrial silhouettes, "
        "stylized wheat-stalks or banner motifs. Generous negative space. "
        "Reference: Aleksandr Deyneka, Vera Mukhina, Vasily Yefanov, Soviet 1940s scientific posters. "
        "Modern minimalist execution with socialist realism DNA — heroic, painterly, propagandistic."
    ),
}


class OpenAIImageGenerator:
    def __init__(self, api_key: str, model: str = "gpt-image-2"):
        self.client = OpenAI(api_key=api_key)
        self.model = model

    def generate_image(
        self,
        prompt: str,
        output_path: str,
        size: str = "1536x1024",
        quality: str = "high",
        background: str = "auto",
    ) -> str:
        kwargs = {
            "model": self.model,
            "prompt": prompt,
            "n": 1,
            "size": size,
            "quality": quality,
            "background": background,
        }

        response = self.client.images.generate(**kwargs)

        if not response.data:
            raise RuntimeError("No image was generated by OpenAI")

        item = response.data[0]
        image_bytes = None

        if getattr(item, "b64_json", None):
            image_bytes = base64.b64decode(item.b64_json)
        elif getattr(item, "url", None):
            import requests

            r = requests.get(item.url, timeout=60)
            r.raise_for_status()
            image_bytes = r.content

        if image_bytes is None:
            raise RuntimeError("OpenAI response did not contain image data")

        output_file = Path(output_path)
        output_file.parent.mkdir(parents=True, exist_ok=True)
        output_file.write_bytes(image_bytes)

        self._strip_metadata(output_file)
        return str(output_file)

    @staticmethod
    def _strip_metadata(image_path: Path) -> None:
        img = cv2.imread(str(image_path), cv2.IMREAD_UNCHANGED)
        if img is not None:
            cv2.imwrite(str(image_path), img)

    def generate_blog_featured_image(
        self,
        topic: str,
        output_path: str,
        style: str = "academic",
        size: str = "1536x1024",
        quality: str = "high",
    ) -> str:
        style_desc = STYLE_PROMPTS.get(style, STYLE_PROMPTS["academic"])

        prompt = (
            f"Create a featured image for a programming blog about: {topic}\n\n"
            f"Requirements:\n"
            f"- {style_desc}\n"
            f"- Professional quality suitable as blog hero image\n"
            f"- 16:9 aspect ratio composition\n"
            f"- Clean, educational aesthetic suitable for tech blog"
        )

        return self.generate_image(prompt, output_path, size=size, quality=quality)
