import base64
from pathlib import Path

import cv2
from openai import OpenAI


STYLE_PROMPTS = {
    "academic": (
        "Black and white line art, textbook figure style, clean white or light gray background, "
        "simple geometric shapes and icons, hand-drawn sketch aesthetic, academic labels, "
        "like a figure from O'Reilly book or IEEE paper. Include a 'Figure 1:' caption at bottom"
    ),
    "tech": (
        "Dark blue/purple gradient background, modern minimalist tech illustration style, "
        "glowing geometric elements, professional quality"
    ),
    "minimal": (
        "Clean white background, simple line art, minimalist design, elegant and professional"
    ),
    "colorful": (
        "Vibrant gradient background, modern flat design, bold colors, eye-catching composition"
    ),
}


class OpenAIImageGenerator:
    def __init__(self, api_key: str, model: str = "gpt-image-2"):
        self.client = OpenAI(api_key=api_key)
        self.model = model

    def generate_image(
        self,
        prompt: str,
        output_path: str,
        size: str = "1536x1024",
        quality: str = "high",
        background: str = "auto",
    ) -> str:
        kwargs = {
            "model": self.model,
            "prompt": prompt,
            "n": 1,
            "size": size,
            "quality": quality,
            "background": background,
        }

        response = self.client.images.generate(**kwargs)

        if not response.data:
            raise RuntimeError("No image was generated by OpenAI")

        item = response.data[0]
        image_bytes = None

        if getattr(item, "b64_json", None):
            image_bytes = base64.b64decode(item.b64_json)
        elif getattr(item, "url", None):
            import requests

            r = requests.get(item.url, timeout=60)
            r.raise_for_status()
            image_bytes = r.content

        if image_bytes is None:
            raise RuntimeError("OpenAI response did not contain image data")

        output_file = Path(output_path)
        output_file.parent.mkdir(parents=True, exist_ok=True)
        output_file.write_bytes(image_bytes)

        self._strip_metadata(output_file)
        return str(output_file)

    @staticmethod
    def _strip_metadata(image_path: Path) -> None:
        img = cv2.imread(str(image_path), cv2.IMREAD_UNCHANGED)
        if img is not None:
            cv2.imwrite(str(image_path), img)

    def generate_blog_featured_image(
        self,
        topic: str,
        output_path: str,
        style: str = "academic",
        size: str = "1536x1024",
        quality: str = "high",
    ) -> str:
        style_desc = STYLE_PROMPTS.get(style, STYLE_PROMPTS["academic"])

        prompt = (
            f"Create a featured image for a programming blog about: {topic}\n\n"
            f"Requirements:\n"
            f"- {style_desc}\n"
            f"- Professional quality suitable as blog hero image\n"
            f"- 16:9 aspect ratio composition\n"
            f"- Clean, educational aesthetic suitable for tech blog"
        )

        return self.generate_image(prompt, output_path, size=size, quality=quality)
